// Backward-compatible re-export from new config location
export {
  // Game dimensions
  GAME_WIDTH,
  GAME_HEIGHT,
  // Battle layout
  BATTLE_GROUND_Y,
  HERO_START_X,
  ENEMY_START_X,
  UNIT_SPACING_Y,
  // Formation
  FRONT_ROW_X,
  BACK_ROW_X,
  FRONT_ROW_AGGRO_BONUS,
  MELEE_RANGE_THRESHOLD,
  // Combat
  BASE_ATTACK_COOLDOWN,
  DAMAGE_VARIANCE,
  CRIT_MULTIPLIER,
  DEFENSE_FORMULA_BASE,
  DEFENSE_SOFT_CAP,
  DEFENSE_SOFT_CAP_FACTOR,
  Y_MOVEMENT_DAMPING,
  // Leveling
  BASE_EXP_REQUIRED,
  EXP_PER_LEVEL,
  MAX_LEVEL,
  // Economy
  STARTING_GOLD,
  NORMAL_BATTLE_GOLD_MIN,
  NORMAL_BATTLE_GOLD_MAX,
  ELITE_BATTLE_GOLD_MIN,
  ELITE_BATTLE_GOLD_MAX,
  BOSS_BATTLE_GOLD,
  // Map
  MAP_NODE_COUNT,
  REST_HEAL_PERCENT,
  REST_TRAIN_EXP,
  REST_SCAVENGE_GOLD_MIN,
  REST_SCAVENGE_GOLD_MAX,
  MAP_SHORTCUT_CHANCE,
  MAP_HIDDEN_NODE_CHANCE,
  MAP_HIDDEN_NODE_COST,
  CLERIC_ENERGY_MULTIPLIER,
  // Equipment
  EQUIPMENT_SLOTS,
  MAX_TEAM_SIZE,
  // Animation
  IDLE_FRAMES,
  WALK_FRAMES,
  ATTACK_FRAMES,
  HURT_FRAMES,
  DEATH_FRAMES,
  ATTACK_DAMAGE_FRAME,
  // UI
  HEALTH_BAR_WIDTH,
  HEALTH_BAR_HEIGHT,
  DAMAGE_NUMBER_DURATION,
  DAMAGE_NUMBER_RISE,
  // Gauntlet
  GAUNTLET_REWARD_MULTIPLIER,
  // Reaction
  REACTION_DAMAGE_BONUS_CAP,
} from './config/balance';
