// Backward-compatible re-export from new config location
export {
  // Game dimensions
  GAME_WIDTH,
  GAME_HEIGHT,
  // Battle layout
  BATTLE_GROUND_Y,
  HERO_START_X,
  ENEMY_START_X,
  UNIT_SPACING_Y,
  // Combat
  BASE_ATTACK_COOLDOWN,
  DAMAGE_VARIANCE,
  CRIT_MULTIPLIER,
  DEFENSE_FORMULA_BASE,
  Y_MOVEMENT_DAMPING,
  // Leveling
  BASE_EXP_REQUIRED,
  EXP_PER_LEVEL,
  MAX_LEVEL,
  // Economy
  STARTING_GOLD,
  NORMAL_BATTLE_GOLD_MIN,
  NORMAL_BATTLE_GOLD_MAX,
  ELITE_BATTLE_GOLD_MIN,
  ELITE_BATTLE_GOLD_MAX,
  BOSS_BATTLE_GOLD,
  // Map
  MAP_NODE_COUNT,
  REST_HEAL_PERCENT,
  // Equipment
  EQUIPMENT_SLOTS,
  MAX_TEAM_SIZE,
  // Animation
  IDLE_FRAMES,
  WALK_FRAMES,
  ATTACK_FRAMES,
  HURT_FRAMES,
  DEATH_FRAMES,
  ATTACK_DAMAGE_FRAME,
  // UI
  HEALTH_BAR_WIDTH,
  HEALTH_BAR_HEIGHT,
  DAMAGE_NUMBER_DURATION,
  DAMAGE_NUMBER_RISE,
} from './config/balance';
